services:
  - type: web
    name: pinterested
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        value: b54c3b760a125352397c605ca76629f6
      - key: SECRET_KEY_BASE
        value: 3b7d13f6c1e8437c2c7e8fd2ff3d2c8b41e6a4efbbbe8d8a9a9a827530d8e6e4a8e2e33b6a6a2c1a2d3a4b5c6d7e8f9g
