services:
  - type: web
    name: pinterested
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: SECRET_KEY_BASE
        value: ${SECRET_KEY_BASE}
      - key: RAILS_MASTER_KEY
        value: ${RAILS_MASTER_KEY}
