services:
  - type: web
    name: pinterested
    env: ruby
    buildCommand: bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        value: b54c3b760a125352397c605ca76629f6
      - key: AWS_ACCESS_KEY_ID
        value: your_aws_access_key_id
      - key: AWS_SECRET_ACCESS_KEY
        value: your_aws_secret_access_key
      - key: AWS_REGION
        value: us-east-2
      - key: AWS_BUCKET_NAME
        value: pinterest25
      - key: WEB_CONCURRENCY
        value: 2
